# Task: Find Correct Relume Project & Verify Content

- [ ] **Identify Correct Relume Project** <!-- id: 0 -->
    - [x] Analyze "MezTa 8" (Current) - *Found to be incomplete* <!-- id: 1 -->
    - [x] Analyze "MezTal 7" - *Flat structure* <!-- id: 2 -->
    - [x] Analyze "MezTal 6" - *Flat structure* <!-- id: 3 -->
    - [x] Analyze "MezTal 5" - *Promising, correct clusters* <!-- id: 4 -->
    - [x] Analyze "MezTal 4" - *Flat, but more pages than 6/7/8* <!-- id: 5 -->
    - [x] Analyze "MezTal 3" - *Flat structure* <!-- id: 6 -->
    - [x] Analyze "MezTal 2" - *Flat structure* <!-- id: 7 -->
    - [x] Analyze "MezTal 1" - *Flat structure* <!-- id: 8 -->
    - [x] Analyze "MezTal Information Architecture" - *Flat structure* <!-- id: 9 -->
    - [x] Analyze "Relume Prompt (Compressed)" - *Minimal structure* <!-- id: 10 -->
    - [x] Select best matching project - *MezTal Information Architecture selected as best base* <!-- id: 11 -->
- [x] **Gap Analysis & Verification** <!-- id: 12 -->
    - [x] Compare selected project sitemap vs `MEZTAL_FULL_SITEMAP_TREE.md` - *Significant gaps in depth found* <!-- id: 13 -->
    - [x] Check for missing "Staff Accountant" cluster - *Missing in all, but Finance cluster exists in MezTal 5* <!-- id: 14 -->
    - [x] Check for missing "Referral Partner" assets - *Missing in all* <!-- id: 15 -->
    - [x] Verify content matches live site scrape - *Content needs injection* <!-- id: 16 -->
- [x] **Analyze Relume Project State** <!-- id: 4 -->
    - [x] Extract sitemaps for all 8 projects <!-- id: 5 -->
    - [x] Identify "MezTal 5" vs "MezTa 8" vs "MezTal IA" structure <!-- id: 6 -->
    - [x] Verify "Ogilvy" content alignment <!-- id: 7 -->
    - [x] **DECISION:** Select **MezTal Information Architecture** as Master Project <!-- id: 8 -->

- [ ] **Phase 1: Hybrid Integration (MezTal IA Base)** <!-- id: 9 -->
    - [ ] **Setup**: Apply Brand Colors (`#F7931E`, `#2D5F8A`) & Typography <!-- id: 10 -->
    - [ ] **Inject Solutions**: Add Sales, Design, Customer Support from MezTa 8 <!-- id: 11 -->
    - [ ] **Inject Operations**: Add Trust & Security, Partners from MezTa 8/6 <!-- id: 12 -->
    - [ ] **Inject Templates**: Add Comparison, Role Landing, Case Study from MezTal 6 <!-- id: 13 -->
    - [ ] **Verify Content**: Check "Ogilvy" copy (Taglines, "Messy Stuff") <!-- id: 14 -->
- [ ] **Update Relume Project (MezTal 5)** <!-- id: 17 -->
    - [ ] Apply Brand Colors (#F7931E, #2D5F8A) <!-- id: 20 -->
    - [ ] Update Home Page Copy (Headlines) <!-- id: 21 -->
    - [ ] Generate Missing "Ogilvy" Pages <!-- id: 27 -->
        - [ ] Why Mexico <!-- id: 28 -->
        - [ ] Why Guadalajara <!-- id: 29 -->
        - [ ] Resources (Hub) <!-- id: 30 -->
        - [ ] Workflow Automation <!-- id: 31 -->
    - [ ] Generate "Staff Accountant" Cluster <!-- id: 18 -->
        - [ ] Role Page <!-- id: 22 -->
        - [ ] Salary Guide <!-- id: 23 -->
        - [ ] Interview Questions <!-- id: 24 -->
        - [ ] Job Description <!-- id: 25 -->
    - [ ] Generate "Referral Partner" Section <!-- id: 26 -->
